"""Base DB config

Revision ID: 41486edd409e
Revises: 
Create Date: 2024-04-08 10:54:04.345933

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41486edd409e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_version',
    sa.Column('app_version_id', sa.Integer(), nullable=False),
    sa.Column('app_version', sa.String(length=255), nullable=True),
    sa.Column('os', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('app_version_id')
    )
    op.create_table('reset_token',
    sa.Column('reset_token_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=255), nullable=True),
    sa.Column('lifespan', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('reset_token_id')
    )
    op.create_table('user',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('admin_level', sa.Integer(), nullable=True),
    sa.Column('phone', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=255), nullable=True),
    sa.Column('account_created', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('reset_token')
    op.drop_table('app_version')
    # ### end Alembic commands ###
